services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb_local
    env_file:
      - ../secrets/.env
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - inception
    ports:
      - 3306:3306
    restart: always
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress_local
    env_file:
      - ../secrets/.env
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx_local
    extra_hosts:
      - "tblochet.42.fr:127.0.0.1"
    env_file:
      - ../secrets/.env
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

volumes:
  wordpress_data:
   driver_opts:
      type: 'none'
      o: bind
      device: /tmp/wordpress_data
  wordpress_db:
   driver_opts:
      type: 'none'
      o: bind
      device: /tmp/wordpress_db

networks:
  inception:
    driver: bridge
