#!/bin/sh
set -xe

if [ ! -e "/build/installed" ]; then
	su mysql -s /bin/sh -c /usr/bin/mariadbd &
	SQLD_PID=$!
	mariadb-admin status --wait

	mariadb -e "CREATE DATABASE IF NOT EXISTS $DATABASE_NAME;" \
		-e "CREATE USER IF NOT EXISTS '$DATABASE_USER'@'%' IDENTIFIED BY '$DATABASE_PASSWORD';" \
		-e "GRANT ALL PRIVILEGES ON $DATABASE_NAME.* TO '$DATABASE_USER'@'%';" \
		-e "FLUSH PRIVILEGES;"

	su mysql -s /bin/sh -c '/usr/bin/mariadb-admin shutdown'
	wait "$SQLD_PID"

	sed -i "s|.*bind-address\s*=.*|bind-address=0.0.0.0|g" /etc/my.cnf.d/mariadb-server.cnf
	sed -i "s|^skip-networking.*|#skip-networking|g" /etc/my.cnf.d/mariadb-server.cnf
	date +install_%s%z > /build/installed
fi

exec su mysql -s /bin/sh -c /usr/bin/mariadbd
