#!/bin/sh

su mysql -s /bin/sh -c /usr/bin/mariadbd &
SQLD_PID=$!
mariadb-admin status --wait
mariadb -e "CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME};"
mariadb -e "CREATE USER IF NOT EXISTS '${DATABASE_USER}'@'%' IDENTIFIED BY '${DATABASE_PASSWORD}';"
mariadb -e "GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO '${DATABASE_USER}'@'%';"
mariadb -e "FLUSH PRIVILEGES;"

su mysql -s /bin/sh -c '/usr/bin/mariadb-admin shutdown'
wait "$SQLD_PID"

sed -i "s|.*bind-address\s*=.*|bind-address=0.0.0.0|g" /etc/my.cnf.d/mariadb-server.cnf

exec su mysql -s /bin/sh -c /usr/bin/mariadbd
