#!/bin/sh
set -xe
/usr/bin/mariadb-admin --host=mariadb --port=3306 --user="$DATABASE_USER" --password="$DATABASE_PASSWORD" --wait status

if ! [ -e /var/www/html/wp-config.php ]; then

	wp core download \
		--locale=en_US \
		--allow-root \
		--path=/var/www/html

	wp config create \
		--dbname=$DATABASE_NAME \
		--dbuser=$DATABASE_USER \
		--dbpass=$DATABASE_PASSWORD \
		--dbhost=$DATABASE_HOST \
		--skip-check \
		--path=/var/www/html \
		--allow-root

	wp core install \
		--url=$DOMAIN \
		--title="$WORDPRESS_TITLE" \
		--admin_user=$WORDPRESS_ADMIN_USER \
		--admin_password=$WORDPRESS_ADMIN_PASSWORD \
		--admin_email=$WORDPRESS_ADMIN_MAIL_ADDRESS \
		--path=/var/www/html \
		--allow-root
		
	wp user create \
		"$WORDPRESS_USER" \
		"$WORDPRESS_MAIL_ADDRESS" \
		--user_pass="$WORDPRESS_PASSWORD" \
		--role=editor \
		--path=/var/www/html
	date +install_%s%z > /build/installed
fi

exec php-fpm -F
